name: Check ZOE (Marathon Mode)

on:
  schedule:
    # Запуск каждые 5 часов (в 0:00, 5:00, 10:00 и т.д.)
    - cron: '0 */5 * * *' 
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    # Ставим тайм-аут 350 минут (чуть меньше 6 часов), чтобы GitHub не считал это ошибкой
    timeout-minutes: 350 

    steps:
    - uses: actions/checkout@v2

    - name: Restore Previous Hash
      uses: actions/cache@v3
      with:
        path: last_hash.txt
        key: zoe-hash-${{ github.run_id }}
        restore-keys: |
          zoe-hash-

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn openvpn-systemd-resolved

    - name: Create VPN config file
      run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: vpn_config.ovpn

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # Запускаем бота. Он будет крутиться в цикле 5 часов 50 минут.
    - name: Run Bot Loop
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: node index.js

    - name: Save Hash
      if: always()
      uses: actions/cache@v3
      with:
        path: last_hash.txt
        key: zoe-hash-${{ github.run_id }}
