name: ZOE Monitor (Header Check)

on:
  schedule:
    # Запуск каждые 5 часов (00:00, 05:00, 10:00, 15:00, 20:00...)
    - cron: '0 */5 * * *'
  workflow_dispatch: # Кнопка

jobs:
  build:
    runs-on: ubuntu-latest
    # Тайм-аут 5 часов 30 минут (страховка)
    timeout-minutes: 330

    steps:
    - uses: actions/checkout@v2

    # 1. ВОССТАНАВЛИВАЕМ ПАМЯТЬ (ЗАГОЛОВОК)
    - name: Restore Previous Header
      uses: actions/cache@v3
      with:
        path: last_header.txt
        # Ключ: zoe-header- + номер запуска. 
        # restore-keys берет ПОСЛЕДНИЙ доступный файл с этим префиксом
        key: zoe-header-${{ github.run_id }}
        restore-keys: |
          zoe-header-

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn openvpn-systemd-resolved

    - name: Create VPN config file
      run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: vpn_config.ovpn
        username: ${{ secrets.VPN_USER }}
        password: ${{ secrets.VPN_PASS }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # 2. ЗАПУСКАЕМ БОТА (Он работает 5 часов и сам выходит)
    - name: Run Bot (5 Hours)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: node index.js

    # 3. СОХРАНЯЕМ ПАМЯТЬ (даже если время вышло)
    - name: Save Header
      if: always()
      uses: actions/cache@v3
      with:
        path: last_header.txt
        key: zoe-header-${{ github.run_id }}
