name: Check ZOE via VPN

on:
  schedule:
    - cron: '*/5 * * * *' # Запуск каждые 5 минут
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 1. Устанавливаем OpenVPN
    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn openvpn-systemd-resolved

    # 2. СОЗДАЕМ ФАЙЛ (Вот этого шага не хватало)
    - name: Create VPN config file
      run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

    # 3. Подключаемся к VPN (теперь указываем путь к созданному файлу)
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: vpn_config.ovpn
        username: ${{ secrets.VPN_USER }}
        password: ${{ secrets.VPN_PASS }}

    # 4. Проверка IP (Убеждаемся, что мы в Украине)
    - name: Check IP
      run: |
        echo "Мой новый IP:"
        curl ifconfig.me
        echo " "

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # 5. Запускаем бота
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: node index.js
